version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    reviewers:
      - NorseDreki
    labels:
      - dependencies
      - dependabot
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(deps):"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
