version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    reviewers:
      - NorseDreki
    labels:
      - dependencies
      - dependabot
    schedule:
      interval: "daily"
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps):"
