version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    reviewers:
      - NorseDreki
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5
    groups:
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - NorseDreki
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
    open-pull-requests-limit: 5
    groups:
      minor:
        update-types:
          - "minor"
      patch:
        update-types:
          - "patch"
