name: Bug Report
description: Report a bug to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: 'NorseDreki'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report.
      options:
        - label: I have searched the existing issues
        - label: I agree to follow this project's Code of Conduct
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output / Screenshots
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks. If applicable, add screenshots to help explain your problem. You can add screenshots by dragging & dropping, selecting or pasting them.
      render: Shell

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide the following information about your environment:
        - OS:
        - Terminal:
        - App Version:
