name: dogcat
base: core22
version: '0.9-RC'
summary: Terminal-based Android Logcat reader with a sane colour scheme
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

#icon: dogcat.png
license: "Apache-2.0"
compression: lzo
grade: stable
confinement: strict
source-code: https://github.com/NorseDreki/dogcat.git
website: https://github.com/NorseDreki/dogcat/

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  dogcat:
    command: dogcat.kexe
    plugs:
      - adb-support
      - process-control
    environment:
      PATH: $SNAP/usr/lib/android-sdk/platform-tools:$PATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/android/

parts:
  dogcat:
    plugin: nil
    source: https://github.com/NorseDreki/dogcat
    source-type: git
    source-branch: main
    # When building with 'snapcraft remote-build', internet is accessed through the proxy
    # Having 'mv' as a separate command after './gradlew' would ignore that 'mv' command
    override-build: |
      if [ -n "${https_proxy:-}" ]; then
          echo $https_proxy
          https_proxy_host=$(echo $https_proxy | cut -d'/' -f3 | cut -d':' -f1)
          https_proxy_port=$(echo $https_proxy | cut -d'/' -f3 | cut -d':' -f2)
          gradle_opts="-Dhttps.proxyHost=$https_proxy_host -Dhttps.proxyPort=$https_proxy_port"
      else
          gradle_opts=""
      fi
      echo $gradle_opts
      
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]]
      then
        ./gradlew $gradle_opts linkReleaseExecutableNativeLinuxX64 \
        && mv build/bin/nativeLinuxX64/releaseExecutable/dogcat.kexe $SNAPCRAFT_STAGE
      fi
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ]]
      then
        ./gradlew $gradle_opts linkReleaseExecutableNativeLinuxArm64 \
        && mv build/bin/nativeLinuxArm64/releaseExecutable/dogcat.kexe $SNAPCRAFT_STAGE
      fi
    override-stage: |
      craftctl default
      mv dogcat.kexe $SNAPCRAFT_PRIME
    build-packages:
      - openjdk-17-jre-headless
      - libncurses-dev
    stage-packages:
      - libncursesw6
      - adb
    # 'organize:' stanza doesn't work, files are not renamed and not placed into target dirs
    # 'stage:' stanza doesn't work, files do exist under $SNAPCRAFT_PART_INSTALL but not copied to $SNAPCRAFT_STAGE
    # Thus, files need to be manually copied across snap steps.
