name: dogcat # you probably want to 'snapcraft register <name>'
base: core22
version: '0.9-RC'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

#icon: htop.png
#license: GPL-2.0

license: "Apache-2.0"
compression: lzo
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
#source-code: https://github.com/gohugoio/hugo.git
#website: https://gohugo.io/

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  dogcat:
    command: dogcat.kexe
    plugs:
      - adb-support
      - process-control
    environment:
      PATH: $SNAP/usr/lib/android-sdk/platform-tools:$PATH
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/android/

parts:
  dogcat:
    plugin: nil
    source: https://github.com/NorseDreki/dogcat
    source-type: git
    source-branch: main
    override-pull: |
      ls
      snapcraftctl pull
    # Having 'mv' as a separate command after './gradlew' would ignore that 'mv' command
    override-build: |
      echo $CRAFT_ARCH_BUILD_FOR
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "amd64" ]]
      then
        ./gradlew linkReleaseExecutableNativeLinuxX64 -Djava.net.useSystemProxies=true \
        && mv build/bin/nativeLinuxX64/releaseExecutable/dogcat.kexe $SNAPCRAFT_STAGE
      fi
      if [[ "$CRAFT_ARCH_BUILD_FOR" == "arm64" ]]
      then
        ./gradlew linkReleaseExecutableNativeLinuxArm64 -Djava.net.useSystemProxies=true \
        && mv build/bin/nativeLinuxArm64/releaseExecutable/dogcat.kexe $SNAPCRAFT_STAGE
      fi
    override-stage: |
      craftctl default
      mv dogcat.kexe $SNAPCRAFT_PRIME
    build-packages:
      - openjdk-17-jre-headless
      - libncurses-dev
    stage-packages:
      - libncursesw6
      - adb
    # 'organize:' stanza doesn't work, files are not renamed and not placed into target dirs
    # 'stage:' stanza doesn't work, files do exist under $SNAPCRAFT_PART_INSTALL but not copied to $SNAPCRAFT_STAGE
    # Thus, files need to be manually copied across snap steps.
