name: Build

on:
  workflow_call:
  pull_request:

permissions:
  contents: write

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest #add macos

    steps:
      - uses: actions/checkout@v4

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # make sure ncurses is installed
      - name: Build with Gradle
        run: ./gradlew assemble
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: build/bin/**/*