name: Check commit message

on: [ pull_request ]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v6
