name: Check formatting

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v3

      - name: Run spotlessCheck and redirect output
        run: ./gradlew spotlessCheck > spotless-output.txt 2>&1 || echo "failed" > spotless-status.txt
        shell: bash

      - name: Use output
        run: |
          SPOTLESS_STATUS=$(cat spotless-status.txt)
          SPOTLESS_OUTPUT=$(cat spotless-output.txt)
          echo "SPOTLESS_STATUS=$SPOTLESS_STATUS" >> $GITHUB_ENV
          echo "SPOTLESS_OUTPUT=$SPOTLESS_OUTPUT" >> $GITHUB_ENV

      - name: Create comment
        if: env.SPOTLESS_STATUS == 'failed'
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const spotless_status = process.env.SPOTLESS_STATUS;
            const spotless_output = process.env.SPOTLESS_OUTPUT;
            await github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              body: `Spotless check failed with the following output:\n\n\`\`\`\n${spotless_output}\n\`\`\``
            });

