name: "Check semantics of PR title and commits"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  contents: read  

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: wagoid/commitlint-github-action@v6