name: Build and Release Snap

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1

      #    - name: Test the package
      #      run: |
      #        sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
      #        dvc version
      #        sudo snap remove dvc

      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
          retention-days: 7

      - name: Publish snap
        uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge