name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  check-gradle-wrapper:
    uses: NorseDreki/dogcat/.github/workflows/check-gradle-wrapper.yml@main

  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract release notes
        id: release_notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          release_notes_file: RELEASE_NOTES.md

      - name: Upload release notes
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: RELEASE_NOTES.md

  build:
    needs: check-gradle-wrapper
    uses: NorseDreki/dogcat/.github/workflows/build.yml@main

  release-brew:
    needs: build
    uses: NorseDreki/dogcat/.github/workflows/release-brew.yml@main
    secrets: inherit

  release-snap:
    needs: build
    uses: NorseDreki/dogcat/.github/workflows/release-snap.yml@main
    secrets: inherit

  create-release:
    needs: [ build, release-notes ]
    runs-on: ubuntu-latest
    steps:
      - name: Download release notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
