name: Build and Release Snap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan/cache
          key: ${{ runner.os }}-gradle-konan-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-konan-

      - name: Build snap
        id: snapcraft
        uses: snapcore/action-build@v1

      - name: Test the package
        run: |
          sudo snap install dogcat --channel=candidate
          dogcat -v
          sudo snap remove dogcat

      #    - name: Test the package
      #      run: |
      #        sudo snap install --dangerous --classic ${{ steps.snapcraft.outputs.snap }}
      #        dvc version
      #        sudo snap remove dvc

      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}
          if-no-files-found: error
          retention-days: 7

      - name: Publish snap
        uses: snapcore/action-publish@v1
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: candidate
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAP_LOGIN }}