name: Release to Homebrew

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bump formulae
        if: startsWith(github.ref, 'refs/tags/')
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.PAT }}
          tap: NorseDreki/tap
          formula: dogcat
          no_fork: true