name: build and publish

on:
  push:
    branches: [ main ]
    tags:
      - '*'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  checkGradleWrapper:
    uses: NorseDreki/dogcat/.github/workflows/check-gradle-wrapper.yml@main

  build:
    needs: checkGradleWrapper
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Extract release notes
        id: release_notes
        if: startsWith(github.ref, 'refs/tags/')
        uses: ffurrer2/extract-release-notes@v2

  releaseBrew:
    needs: build
    uses: NorseDreki/dogcat/.github/workflows/release-brew.yml@main

  releaseSnap:
    needs: build
    uses: NorseDreki/dogcat/.github/workflows/release-snap.yml@main
    secrets:
      snap: ${{ secrets.SNAP_LOGIN }}

  createRelease:
    needs: [ build, releaseBrew, releaseSnap ]
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.release_notes.outputs.release_notes }}
          files: build/bin/**/**/dogcat.kexe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
