name: MacOS Build

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-10.15, macos-11, macos-12, macos-13, macos-14]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master
        
    - name: Install Formula
      run: |
        brew install ncurses
        brew doctor
        
    - name: Install Kotlin
      uses: sdkman/sdkman-action@master
      with:
        candidate: kotlin
        version: '1.9.22'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew assemble
      continue-on-error: true

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: build/bin/**/*